# Created using wingetcreate 1.1.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.2.0.schema.json

PackageIdentifier: Terrastruct.D2
PackageVersion: 0.1.6
PackageLocale: en-US
Publisher: Terrastruct, Inc.
PublisherUrl: https://terrastruct.com/
PackageName: D2
PackageUrl: https://d2lang.com/
License: MPL-2.0 license
LicenseUrl: https://www.mozilla.org/en-US/MPL/2.0/
ShortDescription: A modern diagram scripting language that turns text to diagrams.
Description: D2 is a modern diagram scripting language that turns text to diagrams. It stands for Declarative Diagramming. Declarative, as in, you describe what you want diagrammed, it generates the image.
Tags:
- diagram
- scripting
- text-to-diagram
ManifestType: defaultLocale
ManifestVersion: 1.2.0

